# Generated by Django 2.1 on 2018-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20180829_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Windows', models.CharField(max_length=50)),
                ('Linux', models.CharField(max_length=50)),
            ],
        ),
    ]
