# Generated by Django 2.1 on 2018-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telemetryFile', models.FileField(upload_to='')),
            ],
        ),
    ]
