# Generated by Django 2.1 on 2018-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_postfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTS_OS_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTS_OS', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CM_OS_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CM_OS', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='CM',
            new_name='TOTAL_MODEL',
        ),
        migrations.RenameField(
            model_name='total_model',
            old_name='Linux',
            new_name='CLIENTS_TOTAL',
        ),
        migrations.RenameField(
            model_name='total_model',
            old_name='Windows',
            new_name='CM_TOTAL',
        ),
    ]
