# Generated by Django 2.1 on 2018-08-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_auto_20180830_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CM_VERSION_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CM_VERSION', models.CharField(max_length=1000)),
            ],
        ),
    ]
