# Generated by Django 2.1 on 2018-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_cm_version_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT_VERSION_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_VERSION', models.CharField(max_length=1000)),
            ],
        ),
    ]
