# Generated by Django 2.1 on 2018-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_media_info_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BACKUP_INFO_MODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BACKUP_INFO', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='LIC_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIC_INFO', models.CharField(max_length=10000)),
            ],
        ),
    ]
