# Generated by Django 2.1 on 2018-08-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_backup_info_model_lic_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LIC_INFO',
            new_name='LIC_INFO_MODEL',
        ),
    ]
