# Generated by Django 2.1 on 2018-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_auto_20180831_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_model_all',
            name='CM_SESSIONS',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
