# Generated by Django 2.1 on 2018-08-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_total_model_all_cm_sessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TOTAL_MODEL_ALL',
            new_name='TOTAL_MODEL_ALL1',
        ),
    ]
